[package]
name = "tensift-lattice"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Lattice reduction and CVP algorithms for tensift"

[dependencies]
tensift-core = { path = "../tensift-core" }
ndarray = { workspace = true }
rug = { workspace = true }
num-traits = { workspace = true }
num-integer = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
lll-rs = { workspace = true }

[[bench]]
name = "lattice_reduction"
harness = false

[dev-dependencies]
criterion = { workspace = true }

