[package]
name = "tensift-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Core types, errors, and utilities for tensift"

[dependencies]
thiserror = { workspace = true }

[[bench]]
name = "primes"
harness = false

[dev-dependencies]
criterion = { workspace = true }
